version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/docker/volumes/proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/docker/volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/docker/volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  sample-api:
    restart: always
    image: sample-api
    build: ./samples/api
    container_name: sample-api
    environment:
      - VIRTUAL_HOST=sampleapi.marcus-vetter.de
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=sampleapi.marcus-vetter.de
      - LETSENCRYPT_EMAIL=mail@marcus-vetter.de

  sample-website:
    restart: always
    image: sample-website
    build: ./samples/website
    container_name: sample-website
    volumes:
      - "/docker/volumes/nginx-sample-website/conf.d/:/etc/nginx/conf.d"
      - "/docker/volumes/config/sample-website/config.js:/usr/share/nginx/html/config.js"
    environment:
      - VIRTUAL_HOST=samplewebsite.marcus-vetter.de
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=samplewebsite.marcus-vetter.de
      - LETSENCRYPT_EMAIL=mail@marcus-vetter.de

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    volumes:
      - "/docker/volumes/nextcloud-db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD_GOES_HERE
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=YOUR_PASSWORD_GOES_HERE

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - VIRTUAL_HOST=nextcloud.marcus-vetter.de
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=nextcloud.marcus-vetter.de
      - LETSENCRYPT_EMAIL=mail@marcus-vetter.de
    volumes:
      - "/docker/volumes/nginx-nextcloud/conf.d/:/etc/nginx/conf.d"
      - "/docker/volumes/nextcloud:/var/www/html"
    depends_on:
      - nextcloud-db
